# Generated by Django 2.1.3 on 2018-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('documentformat', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facultyregister',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('contact', models.IntegerField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=60)),
                ('size', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('report', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Studentregister',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
