# Generated by Django 2.1.3 on 2018-12-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLG', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregister',
            old_name='subject',
            new_name='department',
        ),
    ]
